language: ruby
rvm:
  - 2.2
before_script:
  - gem install awesome_bot
  - gem install danger
script:
  - awesome_bot README.md -w https://matrix.org/blog/home/
  - danger
notifications:
  email: false
